name: Deploy

on:
  push:
    branches:
      - main

jobs:
  tests:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      HOST_AIDN: ${{ secrets.HOST_AIDN }}
      KREATIVE_APPCHAIN: ${{ secrets.KREATIVE_APPCHAIN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DNS }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: NODE_ENV=development yarn lint
      - run: NODE_ENV=development yarn build
      - run: NODE_ENV=development yarn test
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'kreative-id-api'
          heroku_email: 'armaan@kreativeusa.com'
          usedocker: true
